package com.styv3.gridlock;

enum TriggerType {
    TOTEM_RESURRECT,
    CRAFT_ITEM,
    PLACE_BLOCK,
    PLACE_AT_HEIGHT_LIMIT,
    BREAK_BLOCK,
    CONSUME_ITEM,
    KILL_ENTITY,
    KILL_OPPONENT,
    ITEM_FRAME_ITEM,
    DAMAGE_FROM_ENTITY,
    SMELT_ITEM,
    OBTAIN_ITEM,
    SHEAR_ENTITY,
    USE_ITEM_ON_ENTITY,
    HIT_OPPONENT_WITH_ITEM,
    PROJECTILE_HIT_ENTITY,
    PROJECTILE_HIT_OPPONENT,
    FISHING_ROD_OPPONENT,
    IGNITE_OPPONENT
}
